### PR TITLE
Add --webdriver-loglevel cli option of phantomjs

### PR DESCRIPTION
**Pull request by cewald**
I added the option ```--webdriver-loglevel``` from the phantomjs cli to use a different loglevel like described in their documentation. It's just one line and option and your code seems to implement it on the fly.

### CODE REVIEW

**Comment by grantlucas** [comment]
Thanks for the PR!

Would you be able to add this option to the list of options available in the README as well? Under the "Other" available options area. Once that's there I'll get this PR merged.

**Comment by grantlucas** [comment]
Also, since it'd match this PR a bit, would you be interested in adding the `--webdriver-logfile=<val>` option as well? No problem if not, I can add it later, but figured it might be good to add along with this PR's change. 😄

**Comment by cewald** [comment]
Done 😃

**Comment by grantlucas** [comment]
`v1.1.7` released with this feature.

**Pull request merged**
